spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/tricountdb
    username: tricountapiuser
    password: tricountAPI
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.springframework: info
    org.hibernate: info

server:
  port: 8000